language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build || true
deploy:
  provider: heroku
  api_key:
    secure: peIBHwEsRxCEQkQP8SftmMwqh8bzkQlxd6DWofjtFxrG7ElOq8l2zc2my8RbTKZwJMuqkXVQnyqSAVKtugrIAcLeBoyG4QTMOSf23i734EV9ICDkR96eCCp7JfUM6H15Is9NorDAI7cPbeZ5k7rKNyXW2jlrpTujFXn+++HvoIvL/w5kjV8TbOhSpR98czC66regWj+bfXUxZ7g8kFvEybFc0ZKXAzAHeyCFx7/XTssEwTbbcZ4QblWoeiVWB1Y1V91eU84JfwM+eRGGoHdpvOFji5G8Frc8gyHmBldOpkOD2RqvK7jauw7Ibj2G3L8I+DN9bwXDcgjcX0n89p52vcIlaC9y0ryfMkUBMz5UuroFtFdc3EiZan/IWfJfmN+HRFmDESM0c5FHgmj0EPCrn0B32xXZa5METAc1nKzR5iP0nOLUGJwiS8fnSXI7Xd0iQuGebFOC5yzC3eZAd1WQcfcaT4x1X64H/Ka7lZ0UWuWkhXmSLNrF1Oc59/b0+7/2lUTKWQ2JuqahwBKDkFAh8IJ9BBmJkE+ox+WvuxDs7ljVugDR+ID3QZUic1G4qna/igtshOokiBWwJ4gHpZnjCmQbo6M88bRsWiLQf64JehNgNOyrJvPs1Ah+S0mS30tjw05+Yv9tyn6MSJspisQlB6tCZ768SyYBT5SyFzWrLz4=
  app: weather-shoes
  on:
    all_branches: true
    repo: doda2391/group5_final_project
