language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build || true
deploy:
  provider: heroku
  api_key:
    secure: pronH/JbAEjOGKQktDjvzqiGRGnTRHYYWOUlgHLQ5/j87hTuRcZ4rZXNg4PCpiY4daM3SE40z8MVaoneGJI3y230Igfuy8uae2YMtbQGTjkqYGuk/dIGkcVxhBwOvTCfIZYkvxQm8xc+g2kkBHM3MdCGepljczBfnDGPbny1oGMqYmpogaxA0yqUHHR0b52DN6UUIuUIvNYaPPpxW0vmdfzWHHnyvsO7qU6Gpi/qKv91+yqly1VZbq/+UERku2eyLr+Zu9jZujyvauF5y89qVLwwL93SWJDfBeWklcx0/na7tQK5hqtT7xjcvI807MF8MrZk1z+d7L1je4lizk7oFOobSjjbC6FaG3f4IQLfxe+Gyc6l7heEwNIMA42g7Bq6heMxdCiT2RGyO7euz7B/dxWnZhblAKaa4B6j+OQrVM8HU5yLUN2/BvmRAWifK4bBoZK02CKigohhTLPUXh3l4AMsUjIHOqDIPDLaoP/9B0x5kHE5ApmxZYd6ii48Hug/xyLntAawx1N6K7/aNN7DU62qWd+ubGt8zE9O2FAKGUaXbch6YgC6UzmCIpGyMDWRy5NUaJucMuJR9a198OMah2TTyeTdnmgjwe/NsXF6Wt9GqeRksre2DR5vbgo9HbMnopUdMdoKIJyqAsEKnkv2d8oRaJl2WNJpJrPcWfPeSk4=
  app: weather-shoes
  on:
    repo: doda2391/group5_final_project
